# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12a393aea35aebb3d6d122ac930defe936e676d60b038817523039b19fbd36b62cd480c27f35360226f4ba8cfb19a5639adb0d5d77f96b62328a24f82ede43c8

test:
  secret_key_base: 5aee1ebc6ec4df6c59eea9e5493b68f743055ec7d64fecd05402e8e6e12f136e49f93df72bbb85b38ef28cad7a6524ef75c9c5e133573b2e2bf2c5dc4280ceb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
